version: '3'
services:
    usauron:
        container_name: usauron
        build:
            context: .
            dockerfile: Dockerfile
        image: usauron:latest
        ports:
        - 11112:11112